apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  labels:
    app: load-balancer
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 2112
  selector:
    app: example-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: example-server
  name: example-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: example-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: example-server
    spec:
      containers:
        - image: <% API_SERVER_IMAGE_NAME %>
          name: example-server
          ports:
            - containerPort: 2112
