apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  labels:
    app: example-server
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 2112
  selector:
    app: example-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: example-server
  name: example-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example-server
  template:
    metadata:
      labels:
        app: example-server
    spec:
      containers:
        - image: <% API_SERVER_IMAGE_NAME %>
          name: example-server
          env:
            - name: MYSQL_HOST
              value: <% MYSQL_HOST %>
            - name: MYSQL_PORT
              value: 3306
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASS
              value: root
            - name: MYSQL_DATABASE
              value: first
          ports:
            - containerPort: 2112
