apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: api-server
  name: api-server
spec:
  replicas: 3
  selector:
    matchLabels:
      run: api-server
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0%
  template:
    metadata:
      labels:
        run: api-server
    spec:
      containers:
        - image: ${API_SERVER_IMAGE}
          name: api-server
          ports:
            - containerPort: 8080
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: api-server-backend
  labels:
    run: api-server
spec:
  type: NodePort
  selector:
    run: api-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080