name: GCP GKE

on:
  push:
    branches: [ fix/gke-infra ]

jobs:
  apply-environment:
    name: Terraform Develop Staging
    runs-on: ubuntu-latest
    env:
      TF_ACTIONS_VERSION: "0.13.4"
      GOOGLE_SERVICE_KEY: ${{ secrets.GOOGLE_SERVICE_KEY }}
      GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
      GOOGLE_COMPUTE_REGION: ${{ secrets.GOOGLE_COMPUTE_REGION }} # "asia-northeast1"
      GOOGLE_COMPUTE_ZONE: ${{ secrets.GOOGLE_COMPUTE_ZONE }} # "asia-northeast1-a"

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_SERVICE_KEY }}
          export_default_credentials: true

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_ACTIONS_VERSION }}

      - name: Terraform - init
        working-directory: gcp/gke/terraform
        run: terraform init

      - name: Terraform - apply
        working-directory: gcp/gke/terraform
        run: terraform apply -auto-approve